### ISSUE TITLE
Issue while deploying to Azure App Service via Github integration

### ISSUE THREAD

**Issue by RSwarnkar** [weslbo/az-305-topics#1]
Hi, I am trying to deploy this website to Azure App service (free plan) using Github integration. 
But getting error while building this: 

```
The folder 'D:\a\az-305-topics\az-305-topics' does not contain an msbuild solution or packages.config file to restore.
Error: Process completed with exit code 1.
``` 
Is there way to get this working on Azure App Service (ASP.Net 4.8)? If not can this be made to run ?

**Comment by weslbo** [comment]
the web folder is used to power the GitHub page https://weslbo.github.io/az-305-topics/
there is no azure app service in this project

**Comment by RSwarnkar** [comment]
Thanks for answering @weslbo . 
However, I would ove to get this working on an Azure App Service. 
Is there a way to dpeloy this as static website? Any hint would help a much please. (Not much into code development).
